apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app:latest
  labels:
    app: simple-flask-app:latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-flask-app:latest
  template:
    metadata:
      labels:
        app: simple-flask-app:latest
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: simple-flask-app:latest
        image: abhishekverma14/simple-flask-app:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
