apiVersion: v1
kind: Service
metadata:
  name: simple-flask-app
  labels:
    app: simple-flask-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: simple-flask-app
